### ISSUE TITLE
Allow 'Enter' key to complete the Button form for new buttons

### ISSUE THREAD

**Issue by 550grand** [matt8707/ha-fusion#252]
Having to scroll down to the 'Done' button and click it when creating entries is painstaking when setting up dozens and dozens of buttons.

<img width="509" alt="image" src="https://github.com/matt8707/ha-fusion/assets/151095012/56320f4b-13ac-42c0-b0dc-b0306f073b7d">

**Comment by meanaverage** [comment]
I was looking into modifying trapFocus.ts to fix this for my own purposes, but then realized that you can just click anywhere outside of the form and it auto-saves your changes instead of 'escaping' -- so that's my solution for this. Hope you find this helpful.

But, I do think it would be helpful if 'Enter' was trapped to end the form, or if another key could fast-forward to the Done Button. Clicking out of a form to save changes typically is similar to an escape, so the current procedure seems non-standard.

**Comment by matt8707** [comment]
In an input field hit enter to modify and esc to exit modal
