### ISSUE TITLE
FR: Custom:button-card

### ISSUE THREAD

**Issue by simon041988** [matt8707/ha-fusion#27]
First of all thank you so much for your work!

One of the greatest advantages of your previous config was the heavy use of customizable custom:Button-Cards.
Many variants of buttons were added by the community. 

Also, I just love the design of the buttons / cards in your previous config. 

In HA-Fusion the button design is very different and in my opinion the previous buttons looked more clean and more structured.

It would be great if there is a way to reuse the custom:button-cards and style from the previous config.

**Comment by matt8707** [comment]
there is not, this is a fresh start. if you want custom:button-card use lovelace
this will probably never be as customizable

**Comment by rchiileea** [comment]
awww finding this my heart broke just because of what is possible with custom button card and card mod :( 
![Screenshot 2023-05-17 130523](https://github.com/matt8707/ha-fusion/assets/87599807/f3732392-e7c4-4ab0-9590-148067cb6ec6)
![Screenshot 2023-11-16 131334](https://github.com/matt8707/ha-fusion/assets/87599807/ef6f1362-dbe5-492b-ac1f-0a1b5a34081d)

**Comment by anarion80** [comment]
Perhaps petition to [@custom-cards ](https://github.com/custom-cards) to make custom button card version for HA Fusion! 😄
