### ISSUE TITLE
FR: I should be able to define define 'on' state easily in Button

### ISSUE THREAD

**Issue by saya6k** [matt8707/ha-fusion#353]
Since there is template now, I can define preview value.

However, since I can't define when is 'on' or 'off' in button, I need to create every binary_sensor that indicate that define on or off of that button. Which is annoying.

I wish I can just define 'on' or 'off' state of that button with template.

**Comment by realroywalker** [comment]
The change made does appear to have fixed the case sensitivity issue, but unless I miss something there isn't any way to configure what the 'on' state for a given button should be (which this FR requests) - Should we be seeing a new option somewhere to configure this?

**Comment by matt8707** [comment]
* select an entity that is 'off'
* add template (beside entity dropdown) to edit state
* write `on` or any of these https://github.com/matt8707/ha-fusion/blob/1a012c5d111bcd6d781084fafbb93f213491a73d/src/lib/Stores.ts#L30-L54

**Comment by realroywalker** [comment]
Thanks - yes I see the logic now.
I think it would be useful to allow for decoupling the displayed 'state' on the button - for example I have a power socket which I would like to display the power draw attribute as the state for the button (which I now can thanks to the templates) but if I use that the button no longer goes 'on' since the 'state' is none of the values in the 'onStates' array you linked.

If the displayed state and 'on state' where 2 separate templates it would allow for that extra flexibility, since we could use templates to say for example if the entity_id state is > 10 output 'on' (which then matches against your static list).

Hopefully that makes sense and I'm not talking complete rubbish 😄
