### ISSUE TITLE
Q: How to show fusion dashboard without the home assistant ui?

### ISSUE THREAD

**Issue by WendelFelius** [matt8707/ha-fusion#38]
First of all, awesome work on this add-on! Love the homekit-like style. 

Question though, how do I find the url to open so that it doesn't show the home assistant ui (sidebar)? Would love to open this fusion dashboard on an iPad for instance, but without the home assistant 'wrapper'. Adding `?menu=false` and `?view=Bedroom` to the url (within HA) also doesn't work, so I'm guessing I'm missing some important knowledge :-)

Unrelated (FR); since a lot of entities are not supported yet, why not give users the option to simply open the Lovelace modals of HA? Like the default ones, instead of custom fusion modals? Or do so until Fusion supports that entity?

🤘🏻

**Comment by matt8707** [comment]
Thank you. There are two ways to install: docker is completely decoupled from Home Assistant (HA) and doesn't include the HA sidebar; the addon is integrated into HA, but there's no way to hide the sidebar without using something like [Kiosk Mode](https://github.com/NemesisRE/kiosk-mode).

The ?menu=false parameter is for the fusion top drawer menu.

You can't open Lovelace modals because this isn't Lovelace!

**Comment by WendelFelius** [comment]
I get it. Thanks!

**Comment by b0mbays** [comment]
Did you get kiosk mode working with Fusion @WendelFelius? I've just tried it and the sidebar remains 🤔

**Comment by WendelFelius** [comment]
> Did you get kiosk mode working with Fusion @WendelFelius? I've just tried it and the sidebar remains 🤔

Just tried it, but unfortunately I also don't get it to work. Looks like that will only work with Lovelace dashboards as well.

**Comment by matt8707** [comment]
https://github.com/thomasloven/hass-browser_mod can also hide sidebar

**Comment by b0mbays** [comment]
Thanks @matt8707, that works well!

**Comment by Kaspermaat** [comment]
@b0mbays how did you manage to get rid of the sidebar? I'm trying but nothing mens to work...
