### ISSUE TITLE
FR: Long press for brightness

### ISSUE THREAD

**Issue by MrOlof** [matt8707/ha-fusion#44]
I've noticed while testing that it's quite easy to hit the right area of the icon instead of the actual icon when turning it off/on which opens the brightness options.

I would suggest that you introduce a long press on the button to open temperature/brightness rather than specifying regions of the button card.  Especially since color/temperature/brightness is something that isn't as commonly used as on/off and is currently covering 80% of the button card. 

![image](https://github.com/matt8707/ha-fusion/assets/100124559/44e265df-2320-4141-b5d0-1949788a13cc)

**Comment by matt8707** [comment]
This is how HomeKit has implemented it, and it feels wrong at first. However, once you get used to it, it's much faster. I don't want to add long press just because we're used to it in Lovelace. The way I tried to solve it before was by adding double click instead, but it turns out Apple did it best, and that's what I'm after, the best implementation.

Left toggle "shortcut", right settings
![screen](https://github.com/matt8707/ha-fusion/assets/36163594/4d36f09b-6b9b-48f7-a6ae-3abad5ac7983)
